# store data into external drive
# link: https://stackoverflow.com/questions/63657735/store-docker-volume-on-external-hard-drive

# example with django + postgresql

version: '3.9' # optional since v1.27.0
services:

  database:
    restart: always
    # build: . # define dockerfile?
    image: mongo:4.2.8
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: mydb
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      # check persistence
      - ./data/mongo:/media/choppy/WD_BLACK/projects/don-choppy/thesis-msc-2022
    ports:
      - "40487:40487"
    # command: "ls -ld /tmp"
    # command: "echo funcionolawea && mongod --auth && mongod --port 40487" # check auth and exec port

    # test2:
    #   image: nvidia/cuda:10.2-base
    #   command: nvidia-smi
    #   runtime: nvidia
    #   deploy:
    #     resources:
    #       reservations:
    #         devices:
    #           - driver: nvidia
    #             count: 1
    #             capabilities: [ gpu ]


  test:
    image: tensorflow/tensorflow:latest-gpu
    command: python -c "import tensorflow as tf;tf.test.gpu_device_name()"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ gpu ]
