# store data into external drive
# link: https://stackoverflow.com/questions/63657735/store-docker-volume-on-external-hard-drive

# example with django + postgresql

version: '3.9' # optional since v1.27.0
services:
  db:
    restart: always
    # build: . # define dockerfile?
    image: mongo:4.2.8
    ports:
      - 40487:40487
    environment:
      - name=value
    volumes:
      # check persistence
      - ./data:/media/choppy/WD_BLACK/projects/don-choppy/thesis-msc-2022
    command: "echo funcionolawea && mongod --auth && mongod --port 40487" # check auth and exec port
